#+title Strips and holes
#+subtitle Field Responses from Francesco Pietropaolo

* Input from FP calculation

The raw results are provided as zip archive of tabular data files.
Each has 48 usable files like ~fort.xxx~ with ~xxx=150+i+12*(j-1)~.
There is an extra ~fort.199~ providing an average.

Each file is about 4MB with 10 columns:

1. time in microseconds (in steps of 5 ns);
2. x coordinate, x=0 is induction strip center line
3. y coordinate,
4. z coordinate, anti-drift direction
5. current on central strip, 0
6. current on strip +1
7. current on strip +2
8. current on strip +3
9. current on strip +4
10. current on strip +5

- The current is given in electron/microseconds and is the one induced by 10^3 electrons

- The electric field used for the calculation is 500 V/cm and the temperature is 87.7 K (both as in the 50 liter TPC). 

- The corresponding drift velocity is obtained with the BNL parametrization (verified as Xin suggested).

- First point is at t=0 and drift location 200mm
- Last point is at t ~ 120us and drift location 16.7mm 

- In the same dropbox folder there are now the collection signals as well.

- There are 72 files, numbers from 201 to 272, corresponding to electron trajectories in a 12 x 6 array covering an area of 5 mm (across the strip) x 2.5 mm.

- The normalization is the same (10^3 electrons) as for the induction


These unit tests prepare the input tar file.

#+begin_example
  $ bats -f '(download|unpack|repack)' test/test_fpstrips.bats 
#+end_example

* Diagnostic plots

Using the tar files from above.

#+begin_example
  $ wirecell-pcbro fpstrips-draw -T "FP" data/fpstrips/DV-1000V.tar.gz dv-1000v-paths-fp.pdf
  $ wirecell-pcbro fpstrips-draw -T "FP" data/fpstrips/DV-2000V.tar.gz dv-2000v-paths-fp.pdf
#+end_example

The ~-T~ simply sets a title.  Plots are shown in FP's coordinate system.

* Transform to WCT response JSON file

~wirecell-pcbro~ will produce a WCT response file in JSON format from
these datasets.



  
