#+title: Automating pcbro

* Snakemake

PCBRo provides a main ~Snakefile~ to automate and run various main tasks
in a very reproducible and self-documented manner.

** Main tasks

The main tasks include:

- converting the variety of FP responses to a common Numpy ~.npz~ based format
- producing an intermediate ~.npz~ file with the data in WCT form
- producing fields in canonical WCT format (~.json.bz2~)
- running just decode raw ~.bin~ data
- running WCT sim and raw/sim + sigproc using these fields.
- making various diagnostic plots after various steps above.

** Install

If you do not already have ~snakemake~ available you may want to install
it in your Python ~venv~, (see [[file:install.org]] for details).

#+begin_example
  $ python -m pip install snakemake
#+end_example


** Setup

A few working and product directory locations must be given to the
~Snakefile~ either on the command line or via a small JSON file.  See
[[file:../scripts/snakeit-bv.json]] for an example.  These high level
configuration parameters have some descriptions at the top of the
Snakefile.

The main ~Snakefile~ assumes a "working directory" different than the
source directory.  The working directory must hold the ~.bin~ files and
FP's "raw" FP data files in tar form.  The latter can be produced with
~scripts/get-fpdata.sh~.  Also to be supplied is a file with a list of
timestamps from the collection of ~.bin~ files.

** Running

The main ~snakemake~ command is something like:

#+begin_example
sdir=/path/to/stamps
ddir=/path/to/data
wdir=/path/to/work
snakemake -jall \
    --config \
      stamps="$sdir/rawdata-2020-05-26.stamps" \
      binpat="$ddir/Rawdata_05_26_2020/run01tri/WIB00step18_FEMB_B8_{timestamp}.bin" \
    --directory $wdir <target>
#+end_example

The ~scripts/snakeit.sh~ can be adapted or checked for an example.

The ~<target>~ is one mentioned in the ~Snakefile~ eg ~all~.
